final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/png1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Addidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/png3.png',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/png2.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Jordan Shoes',
    'price': 29.69,
    'imageUrl': 'assets/images/png4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Apple Shoes',
    'price': 22.69,
    'imageUrl': 'assets/images/png6.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '5',
    'title': 'Bacca Bucci Shoes',
    'price': 90.69,
    'imageUrl': 'assets/images/png5.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
];
